version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/transports"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "gomod"
    directory: "/core"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "gomod"
    directory: "/framework"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "gomod"
    directory: "/plugins/compat"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "gomod"
    directory: "/plugins/governance"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "gomod"
    directory: "/plugins/logging"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "gomod"
    directory: "/plugins/modelcatalogresolver"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "gomod"
    directory: "/transports"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
